baseURL = "http://perso.telecom-paris.fr/nicherel"
languageCode = "en-us"
title = "Nicolas Cherel"
theme = "researcher"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

