baseURL = "https://ncherel.github.io"
languageCode = "en-us"
title = "Nicolas Cherel"
theme = "researcher"

disableKinds = ["taxonomy", "term"]

enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  author = "Nicolas Cherel"
  description = "Personal website of Nicolas Cherel"
  math = true

[params.style]  # appearance options (can be omitted)
  fontFamily = "Arial"
  fontSize = 12

[sitemap]
  changeFreq = ''
  disable = false
  filename = "sitemap.xml"
  priority = -1

